name: My Workflow
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        if [ "${GITHUB_REF}" == "refs/heads/master" ]; then
          echo "No se permite hacer push directo a la rama master"
          exit 1
        fi
